// Generated by the Supabase MCP `generate_typescript_types` tool. Regenerate
// after any migration; do not edit by hand. Current as of the 2026-07-24 audit
// fixes (thread-protection helpers, app_user_open, claim_push_endpoint).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          detail: Json
          id: string
          target_id: string | null
          target_kind: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          detail?: Json
          id?: string
          target_id?: string | null
          target_kind?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          detail?: Json
          id?: string
          target_id?: string | null
          target_kind?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          body: string
          created_at: string
          hidden_at: string | null
          hidden_by: string | null
          id: string
          is_staff: boolean
          request_id: string
          sender_id: string
        }
        Insert: {
          body: string
          created_at?: string
          hidden_at?: string | null
          hidden_by?: string | null
          id?: string
          is_staff?: boolean
          request_id: string
          sender_id: string
        }
        Update: {
          body?: string
          created_at?: string
          hidden_at?: string | null
          hidden_by?: string | null
          id?: string
          is_staff?: boolean
          request_id?: string
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_hidden_by_fkey"
            columns: ["hidden_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          kind: Database["public"]["Enums"]["notification_kind"]
          link: string | null
          read_at: string | null
          title: string
          user_id: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          kind: Database["public"]["Enums"]["notification_kind"]
          link?: string | null
          read_at?: string | null
          title: string
          user_id: string
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["notification_kind"]
          link?: string | null
          read_at?: string | null
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      offers: {
        Row: {
          commitment: string | null
          created_at: string
          description: string
          hidden_at: string | null
          hidden_by: string | null
          id: string
          kind: Database["public"]["Enums"]["offer_kind"]
          location_mode: Database["public"]["Enums"]["location_mode"]
          location_text: string | null
          posted_by: string
          spots: number
          status: Database["public"]["Enums"]["offer_status"]
          timeframe: string | null
          title: string
          updated_at: string
        }
        Insert: {
          commitment?: string | null
          created_at?: string
          description: string
          hidden_at?: string | null
          hidden_by?: string | null
          id?: string
          kind: Database["public"]["Enums"]["offer_kind"]
          location_mode?: Database["public"]["Enums"]["location_mode"]
          location_text?: string | null
          posted_by: string
          spots?: number
          status?: Database["public"]["Enums"]["offer_status"]
          timeframe?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          commitment?: string | null
          created_at?: string
          description?: string
          hidden_at?: string | null
          hidden_by?: string | null
          id?: string
          kind?: Database["public"]["Enums"]["offer_kind"]
          location_mode?: Database["public"]["Enums"]["location_mode"]
          location_text?: string | null
          posted_by?: string
          spots?: number
          status?: Database["public"]["Enums"]["offer_status"]
          timeframe?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "offers_hidden_by_fkey"
            columns: ["hidden_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "offers_posted_by_fkey"
            columns: ["posted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          account_status: Database["public"]["Enums"]["account_status"]
          affiliation: Database["public"]["Enums"]["member_affiliation"] | null
          approved_at: string | null
          approved_by: string | null
          bio: string | null
          class_year: number | null
          created_at: string
          full_name: string
          id: string
          location: string | null
          open_to_requests: boolean
          organization: string | null
          role: Database["public"]["Enums"]["user_role"]
          tags: string[]
          title: string | null
        }
        Insert: {
          account_status?: Database["public"]["Enums"]["account_status"]
          affiliation?: Database["public"]["Enums"]["member_affiliation"] | null
          approved_at?: string | null
          approved_by?: string | null
          bio?: string | null
          class_year?: number | null
          created_at?: string
          full_name: string
          id: string
          location?: string | null
          open_to_requests?: boolean
          organization?: string | null
          role: Database["public"]["Enums"]["user_role"]
          tags?: string[]
          title?: string | null
        }
        Update: {
          account_status?: Database["public"]["Enums"]["account_status"]
          affiliation?: Database["public"]["Enums"]["member_affiliation"] | null
          approved_at?: string | null
          approved_by?: string | null
          bio?: string | null
          class_year?: number | null
          created_at?: string
          full_name?: string
          id?: string
          location?: string | null
          open_to_requests?: boolean
          organization?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          tags?: string[]
          title?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          p256dh: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          p256dh: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          p256dh?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          created_at: string
          id: string
          reason: string
          reporter_id: string
          resolved_at: string | null
          resolved_by: string | null
          status: Database["public"]["Enums"]["report_status"]
          target: Database["public"]["Enums"]["report_target"]
          target_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          reason: string
          reporter_id: string
          resolved_at?: string | null
          resolved_by?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          target: Database["public"]["Enums"]["report_target"]
          target_id: string
        }
        Update: {
          created_at?: string
          id?: string
          reason?: string
          reporter_id?: string
          resolved_at?: string | null
          resolved_by?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          target?: Database["public"]["Enums"]["report_target"]
          target_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      requests: {
        Row: {
          created_at: string
          decided_at: string | null
          id: string
          note: string
          offer_id: string
          status: Database["public"]["Enums"]["request_status"]
          student_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          decided_at?: string | null
          id?: string
          note: string
          offer_id: string
          status?: Database["public"]["Enums"]["request_status"]
          student_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          decided_at?: string | null
          id?: string
          note?: string
          offer_id?: string
          status?: Database["public"]["Enums"]["request_status"]
          student_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "requests_offer_id_fkey"
            columns: ["offer_id"]
            isOneToOne: false
            referencedRelation: "offers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "requests_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_overview: { Args: never; Returns: Json }
      app_has_request_from: { Args: { p_student: string }; Returns: boolean }
      app_has_request_on_offer: { Args: { p_offer: string }; Returns: boolean }
      app_is_active: { Args: never; Returns: boolean }
      app_is_admin: { Args: never; Returns: boolean }
      app_offer_has_requests: { Args: { p_offer: string }; Returns: boolean }
      app_request_has_messages: {
        Args: { p_request: string }
        Returns: boolean
      }
      app_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
      app_user_active: { Args: { p_id: string }; Returns: boolean }
      app_user_open: { Args: { p_id: string }; Returns: boolean }
      claim_push_endpoint: { Args: { p_endpoint: string }; Returns: undefined }
      community_stats: { Args: never; Returns: Json }
    }
    Enums: {
      account_status: "pending" | "active" | "disabled"
      location_mode: "in_person" | "remote" | "flexible"
      member_affiliation: "alumni" | "parent" | "faculty_staff" | "friend"
      notification_kind:
        | "request_received"
        | "request_update"
        | "message_received"
        | "account_update"
        | "offer_moderated"
        | "report_update"
      offer_kind:
        | "internship"
        | "job"
        | "shadow_day"
        | "mentorship"
        | "project_help"
        | "career_chat"
        | "other"
      offer_status: "draft" | "open" | "filled" | "closed"
      report_status: "open" | "resolved" | "dismissed"
      report_target: "user" | "offer" | "message"
      request_status:
        | "sent"
        | "in_conversation"
        | "accepted"
        | "declined"
        | "withdrawn"
      user_role: "student" | "member" | "admin"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      account_status: ["pending", "active", "disabled"],
      location_mode: ["in_person", "remote", "flexible"],
      member_affiliation: ["alumni", "parent", "faculty_staff", "friend"],
      notification_kind: [
        "request_received",
        "request_update",
        "message_received",
        "account_update",
        "offer_moderated",
        "report_update",
      ],
      offer_kind: [
        "internship",
        "job",
        "shadow_day",
        "mentorship",
        "project_help",
        "career_chat",
        "other",
      ],
      offer_status: ["draft", "open", "filled", "closed"],
      report_status: ["open", "resolved", "dismissed"],
      report_target: ["user", "offer", "message"],
      request_status: [
        "sent",
        "in_conversation",
        "accepted",
        "declined",
        "withdrawn",
      ],
      user_role: ["student", "member", "admin"],
    },
  },
} as const
